### PR TITLE
Remove package.json hard paths and add lifecycle stages

### PR DESCRIPTION
**Pull request by bcomnes**
> never include the path to node_modules/.bin/
> Just trust the PATH environ.
- https://twitter.com/izs/status/657976995326726144
- https://twitter.com/izs/status/657977615228104704

Just cleaning up the package.json scripts a little bit, and added a coupe lifecycle steps where it made sense.

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
I don't trust the PATH environ :( this has bitten me quite often and failed to work, but lets give it another shot..

**Comment by Dignifiedquire** [comment]
Could you please change the commit message to something like `chore: Remove package.json hard paths and add lifecycle stages` trying to get an automated changelog from the commit messages. See [this](https://github.com/ipfs/station/blob/master/CONTRIBUTING.md#making-changes) for details

**Comment by bcomnes** [comment]
Sure.

**Comment by bcomnes** [comment]
Should be good to go!

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Comment by jbenet** [comment]
Ugh, i never trust npm to have set $PATH correctly. in my experience, it leads to pain and suffering.

**Comment by VictorBjelkholm** [comment]
Same here, never worked for me somehow...

**Comment by Dignifiedquire** [comment]
@jbenet I don't either, but izs said on twitter so confident that it should work that I suggest we all start using it and file issues on npm and bug him on twitter until it gets fixed :)

**Comment by bcomnes** [comment]
I've never had a problem and it provides a compatibility layer when npm changes how `node_modules` moves things around.

**Pull request merged**
